# Generated by Django 5.2.6 on 2025-10-10 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField(blank=True, verbose_name='Короткое описание/вступление')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True)),
                ('meta_title', models.CharField(blank=True, help_text='Этот текст показывается в заголовке вкладки браузера и в Google при поиске. Пример: «Аренда кабинетов Zen Studio в Алматы». Если оставить пустым — подставится автоматически из названия страницы.', max_length=255, null=True, verbose_name='Заголовок для поисковиков (Title)')),
                ('meta_description', models.TextField(blank=True, help_text='Короткий абзац, который появляется под заголовком в Google. Опиши в 1-2 предложениях, что человек найдёт на странице. Например: «Уютные кабинеты для консультаций, обучения и терапии в центре Алматы».', null=True, verbose_name='Описание страницы (Description)')),
                ('meta_robots', models.CharField(blank=True, help_text='Указывает, можно ли индексировать страницу. Оставь «index,follow», чтобы страница показывалась в Google. Если временно не нужно — поставь «noindex,nofollow».', max_length=50, null=True, verbose_name='Видимость для поисковиков (Robots)')),
                ('og_image', models.ImageField(blank=True, help_text='Эта картинка отображается, когда вы делитесь ссылкой в WhatsApp, Telegram, Instagram и т.п. Рекомендуемый размер 1200×630 пикселей (широкий баннер).', null=True, upload_to='seo/', verbose_name='Картинка для предпросмотра (OG-image)')),
                ('canonical_url', models.URLField(blank=True, help_text='Используется, если одна страница дублирует другую. Обычно можно не заполнять — сайт сам подставит правильный адрес.', null=True, verbose_name='Каноническая ссылка (Canonical URL)')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание (старое)')),
                ('short_description', models.TextField(blank=True, verbose_name='Короткое описание')),
                ('area_sq_m', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Площадь, м²')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='rooms/', verbose_name='Главное фото')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('equipment_text', models.TextField(blank=True, verbose_name='Оснащение (текст)')),
            ],
            options={
                'verbose_name': 'Кабинет',
                'verbose_name_plural': 'Кабинеты',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Zen Studio', help_text='Название бренда или компании. Показывается в заголовках страниц и в поисковой выдаче. Например: «Zen Studio».', max_length=150, verbose_name='Название сайта')),
                ('default_meta_title', models.CharField(blank=True, help_text='Используется на страницах, где не указан свой SEO Title. Пример: «Zen Studio — аренда кабинетов в Алматы».', max_length=255, null=True, verbose_name='Заголовок по умолчанию (Title)')),
                ('default_meta_description', models.TextField(blank=True, help_text='Общее описание сайта, которое поисковики и соцсети будут показывать на страницах без собственного описания. Пример: «Zen Studio — уютные кабинеты для консультаций, обучения и терапии в центре Алматы».', null=True, verbose_name='Описание по умолчанию (Description)')),
                ('default_meta_robots', models.CharField(blank=True, help_text='Настройка для поисковиков: <b>index,follow</b> — разрешить индексировать и переходить по ссылкам. Обычно лучше оставить так. Если сайт в разработке — поставьте <b>noindex,nofollow</b>.', max_length=50, null=True, verbose_name='Видимость по умолчанию (Robots)')),
                ('default_og_image', models.ImageField(blank=True, help_text='Эта картинка используется, когда у конкретной страницы нет своей. Отображается в WhatsApp, Telegram и соцсетях при отправке ссылки. Рекомендуемый размер: 1200×630 px (широкий баннер).', null=True, upload_to='seo/', verbose_name='Основная картинка для ссылок (OG-image)')),
                ('logo', models.ImageField(blank=True, upload_to='logo/', verbose_name='Логотип')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('instagram_link', models.URLField(blank=True, verbose_name='Instagram')),
                ('whatsapp_admin', models.URLField(blank=True, verbose_name='WhatsApp Администратор')),
                ('whatsapp_bot', models.URLField(blank=True, verbose_name='WhatsApp ИИ-ассистент')),
                ('reviews_link', models.URLField(blank=True, verbose_name='Ссылка на отзывы')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='PageContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('img_text', 'Картинка + текст'), ('carousel', 'Карусель изображений'), ('text', 'Только текст')], default='img_text', max_length=32, verbose_name='Тип блока')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок блока / Название карусели')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pages/blocks/', verbose_name='Изображение (для IMG+TEXT)')),
                ('align', models.CharField(choices=[('left', 'Картинка слева, текст справа'), ('right', 'Картинка справа, текст слева'), ('full', 'Широкий блок')], default='left', max_length=16, verbose_name='Раскладка')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='main.page')),
            ],
            options={
                'verbose_name': 'Контент-блок',
                'verbose_name_plural': 'Контент-блоки',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ContentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pages/blocks/carousel/', verbose_name='Файл')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Подпись')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.pagecontentblock')),
            ],
            options={
                'verbose_name': 'Изображение в карусели',
                'verbose_name_plural': 'Изображения в карусели',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rooms/gallery/', verbose_name='Изображение')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.room')),
            ],
            options={
                'verbose_name': 'Изображение кабинета',
                'verbose_name_plural': 'Изображения кабинетов',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RoomInfoBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('description', 'Описание кабинета')], max_length=20, verbose_name='Раздел')),
                ('title', models.CharField(max_length=120, verbose_name='Подраздел / Заголовок')),
                ('value', models.TextField(blank=True, verbose_name='Значение / Описание')),
                ('icon_class', models.CharField(blank=True, max_length=100, verbose_name='Иконка (Font Awesome)')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_blocks', to='main.room', verbose_name='Кабинет')),
            ],
            options={
                'verbose_name': 'Инфо-пункт кабинета',
                'verbose_name_plural': 'Инфо-пункты кабинета',
                'ordering': ['category', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RoomLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта (lat)')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота (lng)')),
                ('map_link', models.URLField(blank=True, verbose_name='Ссылка на карту (Яндекс/Google/2GIS)')),
                ('route_image', models.ImageField(blank=True, null=True, upload_to='rooms/routes/', verbose_name='Схема проезда (изображение)')),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='main.room', verbose_name='Кабинет')),
            ],
            options={
                'verbose_name': 'Локация кабинета',
                'verbose_name_plural': 'Локация кабинета',
            },
        ),
        migrations.CreateModel(
            name='RoomVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок (необязательно)')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='rooms/videos/', verbose_name='Видео-файл (MP4)')),
                ('embed_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на видео (YouTube/Vimeo)')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='rooms/videos/posters/', verbose_name='Обложка (постер)')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='main.room', verbose_name='Кабинет')),
            ],
            options={
                'verbose_name': 'Видео кабинета',
                'verbose_name_plural': 'Видео кабинетов',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HeroSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slider/', verbose_name='Изображение')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sliders', to='main.sitesettings', verbose_name='Сайт')),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайды',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.PositiveIntegerField(verbose_name='Количество часов')),
                ('unit', models.CharField(choices=[('ЧАС', 'ЧАС'), ('ЧАСА', 'ЧАСА'), ('ЧАСОВ', 'ЧАСОВ')], default='ЧАС', max_length=10, verbose_name='Ед.измерения')),
                ('price', models.PositiveIntegerField(verbose_name='Цена, тг')),
                ('persons_text', models.CharField(blank=True, max_length=50, verbose_name='Кол-во человек (текст)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='main.sitesettings', verbose_name='Сайт')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
                'ordering': ['order', 'id'],
            },
        ),
    ]
