# Generated by Django 5.2.6 on 2025-10-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='google_calendar_id',
            field=models.CharField(blank=True, help_text='Скопируйте сюда ID календаря из настроек Google Calendar (вида xxx@group.calendar.google.com)', max_length=255, verbose_name='ID Google Календаря'),
        ),
    ]
