# Generated by Django 5.2.6 on 2025-10-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_room_google_calendar_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='hourly_rate',
            field=models.PositiveIntegerField(blank=True, help_text='Используется для расчета итоговой цены при бронировании. Не показывается на главной.', null=True, verbose_name='Часовая ставка для расчета, тг/час'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Цена для показа на сайте, тг'),
        ),
    ]
