# Generated by Django 5.2.6 on 2025-10-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_tariff_hourly_rate_alter_tariff_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tariff',
            name='hourly_rate',
        ),
        migrations.AlterField(
            model_name='tariff',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Цена, тг'),
        ),
    ]
