# Generated by Django 5.2.6 on 2025-10-17 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_tariff_hourly_rate_alter_tariff_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_duration_hours', models.DecimalField(decimal_places=1, default=0.5, help_text='Цена применяется, если бронь >= этой длительности (например, 0.5, 1.0, 3.0)', max_digits=4, verbose_name='Минимальная длительность (часы)')),
                ('max_people', models.PositiveIntegerField(default=1, help_text='Цена применяется, если гостей <= этому числу', verbose_name='Максимум человек')),
                ('price_per_hour', models.PositiveIntegerField(help_text='Стоимость одного часа аренды при этих условиях', verbose_name='Цена за час (тг)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=0, help_text='Чем меньше, тем выше приоритет (сначала проверяются более специфичные цены)', verbose_name='Порядок')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='main.room', verbose_name='Кабинет')),
            ],
            options={
                'verbose_name': 'Цена кабинета',
                'verbose_name_plural': 'Цены кабинета',
                'ordering': ['room', 'order', 'max_people', 'min_duration_hours'],
            },
        ),
    ]
