# Generated by Django 5.2.6 on 2025-10-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_roomprice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomprice',
            options={'ordering': ['room', 'order', 'min_people'], 'verbose_name': 'Ценовое правило (по группе людей)', 'verbose_name_plural': 'Ценовые правила (по группам людей)'},
        ),
        migrations.RemoveField(
            model_name='roomprice',
            name='min_duration_hours',
        ),
        migrations.AddField(
            model_name='roomprice',
            name='min_people',
            field=models.PositiveIntegerField(default=1, help_text='Нижняя граница группы (включительно)', verbose_name='Минимум человек в группе'),
        ),
        migrations.AlterField(
            model_name='roomprice',
            name='max_people',
            field=models.PositiveIntegerField(default=3, help_text='Верхняя граница группы (включительно)', verbose_name='Максимум человек в группе'),
        ),
        migrations.AlterField(
            model_name='roomprice',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Правила проверяются по порядку. Ставьте более специфичные (узкие) диапазоны выше.', verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='roomprice',
            name='price_per_hour',
            field=models.PositiveIntegerField(help_text='Стоимость одного часа аренды для указанного диапазона людей', verbose_name='Цена за час для этой группы (тг)'),
        ),
    ]
