# Generated by Django 5.2.6 on 2025-10-17 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_roomprice_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='google_calendar_id',
        ),
        migrations.DeleteModel(
            name='RoomPrice',
        ),
    ]
