# Generated by Django 5.2.6 on 2025-10-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_room_google_calendar_id_delete_roomprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='google_calendar_id',
            field=models.CharField(blank=True, help_text='Скопируйте сюда ID календаря из настроек Google Calendar (вида xxx@group.calendar.google.com)', max_length=255, verbose_name='ID Google Календаря'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='hourly_rate',
            field=models.PositiveIntegerField(blank=True, help_text='Используется для расчета итоговой цены при бронировании. Не показывается на главной.', null=True, verbose_name='Часовая ставка для расчета, тг/час'),
        ),
    ]
