# Generated by Django 5.2.6 on 2025-10-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_room_google_calendar_id_tariff_hourly_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingPriceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Стандарт', max_length=100, verbose_name='Название правила (для админки)')),
                ('min_duration_hours', models.DecimalField(decimal_places=1, default=0.5, help_text='Правило сработает, если бронь >= этой длительности', max_digits=4, verbose_name='Минимальная длительность (часы)')),
                ('min_people', models.PositiveIntegerField(default=1, verbose_name='Минимум человек')),
                ('max_people', models.PositiveIntegerField(default=99, verbose_name='Максимум человек')),
                ('price_per_hour', models.PositiveIntegerField(verbose_name='Цена за час (тг)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('order', models.PositiveIntegerField(default=0, help_text='Чем меньше число, тем выше приоритет (0 - самый высокий)', verbose_name='Приоритет')),
            ],
            options={
                'verbose_name': 'Правило расчета цены',
                'verbose_name_plural': 'Правила расчета цены',
                'ordering': ['order', '-min_duration_hours', '-max_people'],
            },
        ),
        migrations.RemoveField(
            model_name='tariff',
            name='hourly_rate',
        ),
    ]
