# Generated by Django 5.2.6 on 2025-10-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_bookingpricerule_remove_tariff_hourly_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceMatrixRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(default='1-3 чел', help_text="Текстовое описание группы (напр., '1-3 чел', '4-8 чел'). Используется для группировки в админке.", max_length=50, verbose_name='Группа (текст)')),
                ('min_people', models.PositiveIntegerField(default=1, verbose_name='Мин. человек')),
                ('max_people', models.PositiveIntegerField(default=3, verbose_name='Макс. человек')),
                ('hours', models.DecimalField(decimal_places=1, help_text="Укажите точное количество часов (например, 1.0, 2.5, 20.0). Для '>= X' укажите X.", max_digits=4, verbose_name='Точное кол-во часов')),
                ('is_minimum_hours', models.BooleanField(default=False, help_text="Отметьте, если 'Часы' означают 'X часов и более' (как для '≥ 20').", verbose_name='Это минимальные часы? (>=)')),
                ('total_price', models.PositiveIntegerField(help_text='Полная стоимость аренды для этой группы и этой длительности.', verbose_name='Итоговая цена за это кол-во часов (тг)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Строка прайс-листа',
                'verbose_name_plural': 'Прайс-лист (матрица цен)',
                'ordering': ['group_name', 'hours'],
                'unique_together': {('min_people', 'max_people', 'hours', 'is_minimum_hours')},
            },
        ),
        migrations.DeleteModel(
            name='BookingPriceRule',
        ),
    ]
