# Generated by Django 5.2.6 on 2025-10-18 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_pricematrixrule_delete_bookingpricerule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PriceMatrixRule',
        ),
    ]
