# Generated by Django 5.2.6 on 2025-10-18 13:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_delete_pricematrixrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='work_time_end',
            field=models.TimeField(blank=True, default=datetime.time(23, 0), help_text='Время окончания работы кабинета (ЧЧ:ММ). Если пусто, используется 23:00.', null=True, verbose_name='Конец рабочего дня'),
        ),
        migrations.AddField(
            model_name='room',
            name='work_time_start',
            field=models.TimeField(blank=True, default=datetime.time(7, 0), help_text='Время начала работы кабинета (ЧЧ:ММ). Если пусто, используется 07:00.', null=True, verbose_name='Начало рабочего дня'),
        ),
    ]
