# Generated by Django 5.2.6 on 2025-10-18 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_pendingbooking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PendingBooking',
        ),
    ]
