# Generated by Django 5.2.6 on 2025-10-18 14:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_delete_pendingbooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Время начала')),
                ('end_time', models.DateTimeField(verbose_name='Время окончания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('expires_at', models.DateTimeField(verbose_name='Истекает в')),
                ('hold_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.room', verbose_name='Кабинет')),
            ],
            options={
                'verbose_name': 'Временный резерв (15 мин)',
                'verbose_name_plural': 'Временные резервы (15 мин)',
                'indexes': [models.Index(fields=['room', 'start_time', 'end_time'], name='main_pendin_room_id_712736_idx'), models.Index(fields=['expires_at'], name='main_pendin_expires_3e34b1_idx')],
            },
        ),
    ]
