# Generated by Django 5.2.6 on 2025-11-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_pendingbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingbooking',
            name='google_event_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID события в Google'),
        ),
    ]
