# Generated by Django 4.2.27 on 2025-12-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_pendingbooking_google_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingbooking',
            name='client_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя клиента'),
        ),
        migrations.AddField(
            model_name='pendingbooking',
            name='client_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Телефон клиента'),
        ),
    ]
