# Generated by Django 4.2.27 on 2025-12-17 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_pendingbooking_client_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, verbose_name='Текст кнопки')),
                ('url', models.URLField(verbose_name='Ссылка')),
                ('style', models.CharField(choices=[('primary', 'Зеленая (Основная)'), ('outline', 'Прозрачная (Контур)'), ('dark', 'Черная')], default='primary', max_length=20, verbose_name='Стиль')),
                ('icon_class', models.CharField(blank=True, max_length=50, verbose_name='Иконка (Font Awesome)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottom_links', to='main.page', verbose_name='Страница')),
            ],
            options={
                'verbose_name': 'Кнопка-ссылка',
                'verbose_name_plural': 'Кнопки-ссылки внизу',
                'ordering': ('order', 'id'),
            },
        ),
    ]
