# Generated by Django 4.2.27 on 2025-12-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_pagelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='hide_phone_in_calendar',
            field=models.BooleanField(default=False, help_text='Если галочка стоит, номер клиента НЕ попадет в Google Календарь (для партнерских кабинетов).', verbose_name='Скрывать телефон в календаре'),
        ),
        migrations.AddField(
            model_name='room',
            name='show_in_booking',
            field=models.BooleanField(default=True, help_text='Если галочка СНЯТА, этот кабинет нельзя будет выбрать в модуле брони (он исчезнет из списков).', verbose_name='Показывать в модуле бронирования'),
        ),
    ]
