# Generated by Django 4.2.27 on 2025-12-17 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_room_hide_phone_in_calendar_room_show_in_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Например: Telegram, TikTok, Договор оферты', max_length=100, verbose_name='Название')),
                ('url', models.URLField(verbose_name='Ссылка')),
                ('icon_class', models.CharField(blank=True, help_text='Например: fa-telegram, fa-tiktok, fa-file-contract', max_length=50, verbose_name='Иконка (Font Awesome)')),
                ('open_in_new_tab', models.BooleanField(default=True, verbose_name='Открывать в новой вкладке')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footer_links', to='main.sitesettings', verbose_name='Сайт')),
            ],
            options={
                'verbose_name': 'Ссылка в футере',
                'verbose_name_plural': 'Ссылки в футере',
                'ordering': ['order'],
            },
        ),
    ]
