# Generated by Django 4.2.27 on 2026-02-11 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_footerlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: «Zen Алмалы» или «Zen на Абая»', max_length=200, verbose_name='Название филиала')),
                ('short_name', models.CharField(blank=True, help_text='Для кнопок фильтров. Если пусто — берется полное название.', max_length=50, verbose_name='Короткое название')),
                ('photo', models.ImageField(blank=True, help_text='Общее фото здания или входа. Рекомендуемый размер: 600×400 px.', null=True, upload_to='branches/', verbose_name='Фото филиала')),
                ('address', models.CharField(blank=True, help_text='Улица, дом (для отображения в списке филиалов).', max_length=300, verbose_name='Общий адрес')),
                ('description', models.TextField(blank=True, verbose_name='Описание филиала')),
                ('twogis_link', models.URLField(blank=True, verbose_name='Ссылка 2GIS (общая)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='room',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='К какому филиалу относится этот кабинет.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='main.branch', verbose_name='Филиал'),
        ),
    ]
