# Generated by Django 4.2.27 on 2026-02-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_branch_room_branch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Локация', 'verbose_name_plural': 'Локации'},
        ),
        migrations.AddField(
            model_name='pendingbooking',
            name='is_confirmed',
            field=models.BooleanField(default=False, help_text='Если True — админ вручную подтвердил оплату, бронь зафиксирована.', verbose_name='Оплата подтверждена'),
        ),
    ]
