# Generated by Django 4.2.27 on 2026-02-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_branch_options_pendingbooking_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='capacity_max',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Максимальное кол-во гостей. Если пусто — не показывается.', null=True, verbose_name='Макс. кол-во человек'),
        ),
        migrations.AddField(
            model_name='room',
            name='capacity_min',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='Минимальное кол-во гостей (для отображения на карточке).', null=True, verbose_name='Мин. кол-во человек'),
        ),
    ]
