# Generated by Django 4.2.27 on 2026-02-17 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_room_capacity_max_room_capacity_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingbooking',
            name='people_count',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Кол-во людей'),
        ),
        migrations.AddField(
            model_name='pendingbooking',
            name='price',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Цена'),
        ),
    ]
