# Generated by Django 4.2.27 on 2026-02-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_pendingbooking_people_count_pendingbooking_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Например: 2, 1200+, 10тыс+', max_length=20, verbose_name='Цифра')),
                ('text', models.CharField(help_text='Например: года работы, клиентов', max_length=100, verbose_name='Подпись')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Цифра (О нас)',
                'verbose_name_plural': 'Цифры (О нас в цифрах)',
                'ordering': ['order'],
            },
        ),
    ]
